// OOXML → editor document, losslessly.
//
// Rules:
//  - Anything the editor understands becomes editable content, and keeps its
//    original XML (w:pPr, w:rPr, w:tcPr, element attributes) for the writer to patch.
//  - Anything it doesn't understand is kept verbatim as a raw node (visible chip,
//    invisible marker, or placeholder block). Nothing is ever dropped, except
//    w:proofErr and w:lastRenderedPageBreak, which Word regenerates.

import type { Mark, Node as PMNode } from 'prosemirror-model';
import { schema, fieldKind } from '../editor/schema';
import { emuToPx, twipsToPx } from '../units';
import { NS, attr, child, children, find, numAttr, serializeXml } from './xml';
import { gridSkipOf, gridSpanOf, readParaModel, readRunModel, readCellModel, readRowModel, type RunModel } from './props';
import { addLayer, attrString, contentChildren, layerFor, newLayerId, type Layer } from './wrappers';
import { readShape } from './shapes';
import { DEFAULT_THEME, type ThemeColors } from './theme';

export interface RelTarget {
  target: string;
  external: boolean;
}

/** Inline context: marks from enclosing wrappers (hyperlink, sdt, field result ...). */
interface Ctx {
  marks: readonly Mark[];
  layers: string | null; // JSON Layer[]
}

type Emit = (n: PMNode) => void;
type PageBreak = (rPr: string | null, runAttrs: string | null, ctx: Ctx) => void;

/** Invisible or tiny inline things we keep but never show as text. */
const HIDDEN_INLINE = new Set([
  'bookmarkStart', 'bookmarkEnd', 'commentRangeStart', 'commentRangeEnd', 'permStart', 'permEnd',
  'moveFromRangeStart', 'moveFromRangeEnd', 'moveToRangeStart', 'moveToRangeEnd',
  'customXmlInsRangeStart', 'customXmlInsRangeEnd', 'customXmlDelRangeStart', 'customXmlDelRangeEnd',
  'customXmlMoveFromRangeStart', 'customXmlMoveFromRangeEnd', 'customXmlMoveToRangeStart', 'customXmlMoveToRangeEnd',
  'del', 'moveFrom',
]);
/** Wrappers whose content is ordinary inline content. */
const INLINE_WRAPPERS = new Set(['ins', 'moveTo', 'smartTag', 'customXml', 'dir', 'bdo', 'sdt']);
const DROPPED = new Set(['proofErr', 'lastRenderedPageBreak']);

export function modelMarks(m: RunModel): Mark[] {
  const out: Mark[] = [];
  if (m.charStyle) out.push(schema.marks.charStyle.create({ id: m.charStyle }));
  if (m.bold != null) out.push(schema.marks.bold.create({ on: m.bold }));
  if (m.italic != null) out.push(schema.marks.italic.create({ on: m.italic }));
  if (m.underline) out.push(schema.marks.underline.create());
  if (m.strike) out.push(schema.marks.strike.create());
  if (m.superscript) out.push(schema.marks.superscript.create());
  if (m.subscript) out.push(schema.marks.subscript.create());
  if (m.color) out.push(schema.marks.color.create({ color: m.color }));
  if (m.highlight) out.push(schema.marks.highlight.create({ color: m.highlight }));
  if (m.fontFamily || m.fontEastAsia) out.push(schema.marks.font.create({ family: m.fontFamily, eastAsia: m.fontEastAsia }));
  if (m.fontSize != null) out.push(schema.marks.fontSize.create({ pt: m.fontSize }));
  return out;
}

export class Converter {
  private fields: { instr: string; phase: 'instr' | 'result'; hasResult: boolean }[] = [];

  constructor(
    private rels: Map<string, RelTarget>,
    private images: Map<string, string>,
    /** The document's theme colours, for shapes (docx/shapes.ts). */
    private theme: ThemeColors = DEFAULT_THEME,
  ) {}

  // ----- blocks -----

  blocks(container: Element, wrap: string | null = null): PMNode[] {
    const out: PMNode[] = [];
    for (const el of contentChildren(container)) {
      const w = el.namespaceURI === NS.w ? el.localName : '';
      if (w === 'p') out.push(...this.paragraph(el, wrap));
      else if (w === 'tbl') out.push(this.table(el, wrap));
      else if (w === 'sdt' || w === 'customXml') {
        const { layer, content } = layerFor(el);
        const inner = this.blocks(content, addLayer(wrap, layer));
        out.push(...(inner.length ? inner : [this.rawBlock(el, wrap, true)]));
      } else if (['sectPr', 'tblPr', 'tcPr', 'trPr', 'tblGrid', 'tblPrEx', 'pPr'].includes(w)) {
        // Properties of the parent; handled there.
      } else if (DROPPED.has(w)) {
        // Regenerated by Word.
      } else {
        out.push(this.rawBlock(el, wrap, HIDDEN_INLINE.has(w)));
      }
    }
    return out;
  }

  private rawBlock(el: Element, wrap: string | null, hidden: boolean): PMNode {
    return schema.nodes.raw_block.create({ xml: serializeXml(el), label: el.localName, hidden, wrap });
  }

  // ----- paragraphs -----

  paragraph(p: Element, wrap: string | null): PMNode[] {
    const pPr = child(p, 'pPr');
    const sectPr = child(pPr, 'sectPr');
    const attrs: Record<string, unknown> = {
      ...readParaModel(pPr),
      pPr: pPr ? serializeXml(pPr) : null,
      pAttrs: attrString(p) || null,
      sectPr: sectPr ? serializeXml(sectPr) : null,
      wrap,
    };

    // A w:p is split into pieces around page breaks (w:br w:type="page").
    const pieces: PMNode[][] = [[]];
    const breaks: { rPr: string | null; runAttrs: string | null; layers: string | null; href: string | null }[] = [];
    const emit: Emit = (n) => pieces[pieces.length - 1].push(n);
    const pageBreak: PageBreak = (rPr, runAttrs, ctx) => {
      // The wrappers around the break's run (a w:ins ...) are kept on the break.
      const href = ctx.marks.find((m) => m.type === schema.marks.link)?.attrs.href ?? null;
      breaks.push({ rPr, runAttrs, layers: ctx.layers, href });
      pieces.push([]);
    };
    this.inlines(p, { marks: [], layers: null }, emit, pageBreak);

    if (!breaks.length) return [schema.nodes.paragraph.create(attrs, mergeText(pieces[0]))];

    const group = newLayerId();
    const out: PMNode[] = [];
    let keptPara = false;
    // The section break belongs to the w:p's mark, which ends its last piece: only that piece
    // carries it, and a w:p ending with a page break keeps an empty last piece for it.
    const last = pieces.length - 1;
    const kept = (i: number) => pieces[i].length > 0 || (i === last && !!attrs.sectPr);
    pieces.forEach((content, i) => {
      if (i > 0) {
        const b = breaks[i - 1];
        // Remember the paragraph properties when no text piece carries them.
        const para = !keptPara && !pieces.some((_, k) => k >= i && kept(k)) ? JSON.stringify(attrs) : null;
        out.push(schema.nodes.page_break.create({ group, rPr: b.rPr, runAttrs: b.runAttrs, para, wrap, layers: b.layers, href: b.href }));
      }
      // Empty text around a break is not turned into extra paragraphs.
      if (!kept(i)) return;
      out.push(schema.nodes.paragraph.create({ ...attrs, brGroup: group, sectPr: i === last ? attrs.sectPr : null }, mergeText(content)));
      keptPara = true;
    });
    // Breaks before the first surviving piece also need the paragraph properties.
    if (!(out[0].type === schema.nodes.paragraph)) {
      out[0] = schema.nodes.page_break.create({ ...out[0].attrs, para: JSON.stringify(attrs) });
    }
    return out;
  }

  private inlines(parent: Element, ctx: Ctx, emit: Emit, pageBreak: PageBreak): void {
    for (const el of contentChildren(parent)) {
      const w = el.namespaceURI === NS.w ? el.localName : '';
      if (w === 'pPr' || DROPPED.has(w)) continue;
      if (w === 'r') {
        this.run(el, ctx, emit, pageBreak);
      } else if (w === 'hyperlink') {
        const id = attr(el, 'id', NS.r);
        const anchor = attr(el, 'anchor');
        const href = id ? this.rels.get(id)?.target : anchor != null ? '#' + anchor : null;
        const layer: Layer = {
          id: newLayerId(),
          kind: 'link',
          // Everything but the target, which the writer regenerates from the link mark.
          open: attrString(el, (n) => n === 'r:id' || n === 'w:anchor' || /^[\w]+:id$/.test(n) && el.getAttribute(n) === id),
          close: `</${el.tagName}>`,
        };
        const marks = href ? schema.marks.link.create({ href }).addToSet(ctx.marks) : ctx.marks;
        this.wrapped(el, ctx, { marks, layers: addLayer(ctx.layers, layer) }, el, emit, pageBreak);
      } else if (w === 'fldSimple' && isPageField(attr(el, 'instr') ?? '') && el.getElementsByTagNameNS(NS.w, 'r').length <= 1) {
        // A simple page-number field becomes a live field node.
        const instr = (attr(el, 'instr') ?? '').trim();
        const r = child(el, 'r');
        let marks = this.ctxMarks(ctx);
        const rPrEl = child(r, 'rPr');
        for (const m of modelMarks(readRunModel(rPrEl))) marks = m.addToSet(marks);
        if (rPrEl || (r && attrString(r))) marks = schema.marks.run.create({ rPr: rPrEl ? serializeXml(rPrEl) : null, attrs: (r && attrString(r)) || null }).addToSet(marks);
        emit(schema.nodes.field.create({ instr, text: el.textContent ?? '', xml: serializeXml(el) }, null, marks));
      } else if (w === 'fldSimple') {
        const instr = attr(el, 'instr') ?? '';
        const { layer } = layerFor(el);
        const marks = schema.marks.fieldResult.create({ instr: instr.trim() }).addToSet(ctx.marks);
        this.wrapped(el, ctx, { marks, layers: addLayer(ctx.layers, layer) }, el, emit, pageBreak);
      } else if (INLINE_WRAPPERS.has(w)) {
        const { layer, content } = layerFor(el);
        this.wrapped(el, ctx, { marks: ctx.marks, layers: addLayer(ctx.layers, layer) }, content, emit, pageBreak);
      } else if (HIDDEN_INLINE.has(w)) {
        const refs = w === 'del' || w === 'moveFrom' ? this.refsIn(el) : null;
        emit(this.raw(serializeXml(el), w, ctx, refs ? { hidden: true, refs } : { hidden: true }));
      } else if (el.namespaceURI === 'http://schemas.openxmlformats.org/officeDocument/2006/math') {
        emit(this.raw(serializeXml(el), '公式', ctx));
      } else {
        emit(this.raw(serializeXml(el), el.localName, ctx));
      }
    }
  }

  /**
   * Inline content of an element (a rejected w:del / w:moveFrom) placed where a node with
   * `marks` was. A page break inside it cannot split the paragraph here, so its run is kept as-is.
   */
  inlineContent(el: Element, marks: readonly Mark[]): PMNode[] {
    const wrap = marks.find((m) => m.type === schema.marks.inlineWrap);
    const ctx: Ctx = { marks: marks.filter((m) => m !== wrap), layers: wrap ? wrap.attrs.layers : null };
    const out: PMNode[] = [];
    this.inlines(el, ctx, (n) => out.push(n), (rPr, runAttrs, c) =>
      out.push(this.raw(`<w:r${runAttrs ?? ''}>${rPr ?? ''}<w:br w:type="page"/></w:r>`, '分頁符號', c)),
    );
    return mergeText(out);
  }

  /** Pictures and links a kept deletion refers to (by relationship id), for rejecting it later. */
  private refsIn(el: Element): { rels: Record<string, RelTarget>; images: Record<string, string> } | null {
    const rels: Record<string, RelTarget> = {};
    const images: Record<string, string> = {};
    let found = false;
    for (const e of Array.from(el.getElementsByTagName('*'))) {
      for (const a of Array.from(e.attributes)) {
        if (a.namespaceURI !== NS.r) continue;
        const rel = this.rels.get(a.value);
        const img = this.images.get(a.value);
        if (rel) rels[a.value] = rel;
        if (img) images[a.value] = img;
        found ||= !!(rel || img);
      }
    }
    return found ? { rels, images } : null;
  }

  /** Content of a wrapper; an empty wrapper is kept whole as an invisible marker. */
  private wrapped(
    el: Element,
    outer: Ctx,
    inner: Ctx,
    content: Element,
    emit: Emit,
    pageBreak: PageBreak,
  ): void {
    let count = 0;
    this.inlines(content, inner, (n) => {
      count++;
      emit(n);
    }, pageBreak);
    if (!count) emit(this.raw(serializeXml(el), el.localName, outer, { hidden: true }));
  }

  private ctxMarks(ctx: Ctx): readonly Mark[] {
    return ctx.layers ? schema.marks.inlineWrap.create({ layers: ctx.layers }).addToSet(ctx.marks) : ctx.marks;
  }

  private raw(xml: string, label: string, ctx: Ctx, extra: Record<string, unknown> = {}): PMNode {
    return schema.nodes.raw_inline.create({ xml, label, ...extra }, null, this.ctxMarks(ctx));
  }

  private run(r: Element, ctx: Ctx, emit: Emit, pageBreak: PageBreak): void {
    const rPrEl = child(r, 'rPr');
    const rPr = rPrEl ? serializeXml(rPrEl) : null;
    const runAttrs = attrString(r) || null;
    let base: readonly Mark[] = this.ctxMarks(ctx);
    for (const m of modelMarks(readRunModel(rPrEl))) base = m.addToSet(base);
    if (rPr || runAttrs) base = schema.marks.run.create({ rPr, attrs: runAttrs }).addToSet(base);
    // Decided per child: Word may put a whole field (codes and result) in one run.
    let marks = base;

    // Anything kept verbatim is re-wrapped in a run with the same properties.
    const keep = (el: Element, label: string, extra: Record<string, unknown> = {}) =>
      emit(
        schema.nodes.raw_inline.create(
          { xml: `<${r.tagName}${runAttrs ?? ''}>${rPr ?? ''}${serializeXml(el)}</${r.tagName}>`, label, ...extra },
          null,
          marks,
        ),
      );

    for (const el of Array.from(r.children)) {
      const w = el.namespaceURI === NS.w ? el.localName : '';
      if (w === 'rPr' || DROPPED.has(w)) continue;
      const top = this.fields[this.fields.length - 1];
      const inResult = top?.phase === 'result' && w !== 'fldChar' && w !== 'instrText';
      if (inResult) top.hasResult = true;
      marks = inResult ? schema.marks.fieldResult.create({ instr: top.instr.trim() }).addToSet(base) : base;
      switch (w) {
        case 't':
          if (el.textContent) emit(schema.text(el.textContent, marks));
          break;
        case 'tab':
          emit(schema.nodes.tab.create(null, null, marks));
          break;
        case 'br':
          if (attr(el, 'type') === 'page') pageBreak(rPr, runAttrs, ctx);
          else emit(schema.nodes.hard_break.create({ type: attr(el, 'type'), clear: attr(el, 'clear') }, null, marks));
          break;
        case 'cr':
          emit(schema.nodes.hard_break.create({ type: 'cr' }, null, marks));
          break;
        case 'fldChar': {
          const type = attr(el, 'fldCharType');
          if (type === 'begin') this.fields.push({ instr: '', phase: 'instr', hasResult: false });
          else if (type === 'separate' && this.fields.length) this.fields[this.fields.length - 1].phase = 'result';
          else if (type === 'end') {
            const f = this.fields.pop();
            // Word may store a page-number field without a cached result; show the
            // number anyway with a display-only placeholder that writes nothing.
            if (f && !f.hasResult && isPageField(f.instr)) {
              emit(schema.nodes.raw_inline.create({ xml: '', label: '#', plain: true }, null, schema.marks.fieldResult.create({ instr: f.instr.trim() }).addToSet(base)));
            }
          }
          keep(el, 'field', { hidden: true });
          break;
        }
        case 'instrText': {
          const f = this.fields[this.fields.length - 1];
          if (f && f.phase === 'instr') f.instr += el.textContent ?? '';
          keep(el, 'field', { hidden: true });
          break;
        }
        case 'drawing': {
          const img = child(el, 'inline', NS.wp) && find(el, 'pic', NS.pic) ? this.drawing(el, marks) : null;
          if (img) {
            const { src, width, height } = img.attrs;
            emit(img.type.create({ ...img.attrs, xml: serializeXml(el), origSrc: src, origWidth: width, origHeight: height }, null, img.marks));
          }
          else keep(el, find(el, 'chart', NS.c) ? '圖表' : '圖形', { ...this.preview(el), ...this.shape(el) });
          break;
        }
        case 'pict':
          keep(el, '物件', { ...this.preview(el), ...this.shape(el) });
          break;
        case 'object':
          keep(el, '物件', this.preview(el));
          break;
        case 'footnoteReference':
          keep(el, '註腳');
          break;
        case 'endnoteReference':
          keep(el, '章節附註');
          break;
        case 'commentReference':
          keep(el, '註解');
          break;
        case 'sym': {
          const code = parseInt(attr(el, 'char') ?? '', 16);
          keep(el, code ? String.fromCharCode(code >= 0xf000 ? code - 0xf000 : code) : '?', { plain: true });
          break;
        }
        case 'noBreakHyphen':
          keep(el, '‑', { plain: true });
          break;
        case 'softHyphen':
          keep(el, '', { hidden: true });
          break;
        case 'ptab':
          keep(el, ' ', { plain: true });
          break;
        default: {
          // Word 2010+ writes a text box or shape as mc:AlternateContent (DrawingML and VML).
          const shape = el.namespaceURI === NS.mc ? this.shape(el) : {};
          keep(el, shape.shape ? '圖形' : el.localName || '物件', shape);
        }
      }
    }
  }

  /** A text box or shape's model (docx/shapes.ts), as raw_inline attrs; nothing for other drawings. */
  private shape(el: Element): { shape?: unknown } {
    const shape = readShape(el, {
      theme: this.theme,
      image: (id) => this.images.get(id),
      // A text box's content is read like the body (a converter of its own: fields don't continue into it).
      blocks: (txbx) => new Converter(this.rels, this.images, this.theme).blocks(txbx),
      doc: (blocks) => schema.nodes.doc.create(null, blocks.length ? blocks : [schema.nodes.paragraph.create()]),
    });
    return shape ? { shape } : {};
  }

  drawing(d: Element, marks: readonly Mark[]): PMNode | null {
    const blip = find(d, 'blip', NS.a);
    const id = attr(blip, 'embed', NS.r);
    const src = id ? this.images.get(id) : undefined;
    if (!src) return null;
    const extent = find(d, 'extent', NS.wp);
    const docPr = find(d, 'docPr', NS.wp);
    return schema.nodes.image.create(
      {
        src,
        width: extent ? Math.round(emuToPx(Number(extent.getAttribute('cx')))) : null,
        height: extent ? Math.round(emuToPx(Number(extent.getAttribute('cy')))) : null,
        alt: docPr?.getAttribute('descr') ?? '',
      },
      null,
      marks,
    );
  }

  /** A picture to show on screen for kept-as-is drawings, when one exists. */
  private preview(el: Element): Record<string, unknown> {
    const img = this.drawing(el, []) ?? this.vmlImage(el);
    return img ? { src: img.attrs.src, width: img.attrs.width, height: img.attrs.height } : {};
  }

  private vmlImage(el: Element): PMNode | null {
    const data = el.getElementsByTagNameNS('urn:schemas-microsoft-com:vml', 'imagedata')[0];
    const id = data?.getAttributeNS(NS.r, 'id');
    const src = id ? this.images.get(id) : undefined;
    if (!src) return null;
    const style = data.parentElement?.getAttribute('style') ?? '';
    const size = (k: string) => {
      const m = new RegExp(k + ':\\s*([\\d.]+)(pt|px|in)?').exec(style);
      if (!m) return null;
      const v = Number(m[1]);
      return Math.round(m[2] === 'pt' ? (v * 96) / 72 : m[2] === 'in' ? v * 96 : v);
    };
    return schema.nodes.image.create({ src, width: size('width'), height: size('height') });
  }

  // ----- tables -----

  table(tbl: Element, wrap: string | null): PMNode {
    const tblPr = child(tbl, 'tblPr');
    const tblGrid = child(tbl, 'tblGrid');
    // Widths to show the columns with; the file's own w:tblGrid is written back unchanged
    // (tblGridXml) unless a column is resized.
    const grid = displayGrid(tbl, tblPr, children(tblGrid ?? tbl, 'gridCol').map((g) => numAttr(g, 'w') ?? 0));

    interface CellDraft {
      attrs: Record<string, unknown>;
      content: PMNode[];
      col: number;
    }
    interface RowDraft {
      attrs: Record<string, unknown>;
      cells: CellDraft[];
    }
    const rows: RowDraft[] = [];
    const mergeOrigin = new Map<number, CellDraft>(); // grid column -> cell that started a vertical merge

    for (const tr of children(tbl, 'tr')) {
      const trPr = child(tr, 'trPr');
      const tblPrEx = child(tr, 'tblPrEx');
      const row: RowDraft = {
        attrs: {
          trPr: trPr ? serializeXml(trPr) : null,
          trAttrs: attrString(tr) || null,
          tblPrEx: tblPrEx ? serializeXml(tblPrEx) : null,
          ...readRowModel(trPr),
        },
        cells: [],
      };
      // Grid values as used for layout (1..63 columns; see gridSpanOf): a span of 0 or less
      // would never move on to the next column. The XML is kept as written.
      let col = gridSkipOf(trPr, 'gridBefore');
      for (const tc of children(tr, 'tc')) {
        const tcPr = child(tc, 'tcPr');
        const span = gridSpanOf(tcPr);
        const vMergeEl = child(tcPr, 'vMerge');
        const vMerge = vMergeEl ? attr(vMergeEl, 'val') ?? 'continue' : null;
        if (vMerge === 'continue') {
          const origin = mergeOrigin.get(col);
          if (origin) {
            origin.attrs.rowspan = (origin.attrs.rowspan as number) + 1;
            (origin.attrs.mergedTc as string[]).push(serializeXml(tc));
            col += span;
            continue;
          }
        }
        const model = readCellModel(tcPr);
        const content = this.blocks(tc);
        const cell: CellDraft = {
          col,
          attrs: {
            colspan: span,
            rowspan: 1,
            colwidth: pxWidths(grid, col, span),
            background: model.background,
            vAlign: model.vAlign,
            borders: model.borders,
            tcPr: tcPr ? serializeXml(tcPr) : null,
            mergedTc: [],
          },
          content: content.length ? content : [schema.nodes.paragraph.create()],
        };
        if (vMerge === 'restart') mergeOrigin.set(col, cell);
        else mergeOrigin.delete(col);
        row.cells.push(cell);
        col += span;
      }
      rows.push(row);
    }

    // Word allows ragged rows (w:gridBefore / w:gridAfter, or simply fewer cells).
    // Fill the holes with empty "filler" cells so every row covers the whole grid.
    const width = Math.max(grid.length, ...rows.map((r) => r.cells.reduce((m, c) => Math.max(m, c.col + (c.attrs.colspan as number)), 0)));
    const covered: Set<number>[] = rows.map(() => new Set<number>());
    const rowNodes = rows.map((row, r) => {
      const out: CellDraft[] = [];
      const byCol = new Map(row.cells.map((c) => [c.col, c]));
      let c = 0;
      while (c < width) {
        const cell = byCol.get(c);
        if (cell) {
          const rowspan = Math.min(cell.attrs.rowspan as number, rows.length - r);
          cell.attrs.rowspan = rowspan;
          for (let k = 1; k < rowspan; k++) for (let j = 0; j < (cell.attrs.colspan as number); j++) covered[r + k].add(c + j);
          if (!(cell.attrs.mergedTc as string[]).length) cell.attrs.mergedTc = null;
          out.push(cell);
          c += cell.attrs.colspan as number;
        } else if (covered[r].has(c)) {
          c++;
        } else {
          let n = 1;
          while (c + n < width && !byCol.has(c + n) && !covered[r].has(c + n)) n++;
          out.push({ col: c, attrs: { colspan: n, rowspan: 1, colwidth: pxWidths(grid, c, n), filler: true }, content: [schema.nodes.paragraph.create()] });
          c += n;
        }
      }
      return schema.nodes.table_row.create(row.attrs, out.map((d) => schema.nodes.table_cell.create(d.attrs, d.content)));
    });
    if (!rowNodes.length) {
      rowNodes.push(schema.nodes.table_row.create(null, [schema.nodes.table_cell.create(null, schema.nodes.paragraph.create())]));
    }
    return schema.nodes.table.create(
      {
        styleId: attr(child(tblPr, 'tblStyle'), 'val'),
        tblPr: tblPr ? serializeXml(tblPr) : null,
        grid: grid.length ? grid : null,
        tblGridXml: tblGrid ? serializeXml(tblGrid) : null,
        wrap,
      },
      rowNodes,
    );
  }
}

function isPageField(instr: string): boolean {
  return ['PAGE', 'NUMPAGES', 'SECTIONPAGES'].includes(fieldKind(instr));
}

/**
 * Column widths (twips) to show a table with: normally its w:tblGrid. Some generators write
 * a placeholder grid (e.g. every column 100 twips) and rely on the cells' w:tcW, which Word
 * uses to lay out auto-fit tables. For those, the widths come from the row whose cells all
 * give a width (the one with the most cells); failing that, the grid is stretched to w:tblW.
 * Fixed-layout tables always use their grid, as Word does.
 */
function displayGrid(tbl: Element, tblPr: Element | null, grid: number[]): number[] {
  if (!grid.length || attr(child(tblPr, 'tblLayout'), 'type') === 'fixed') return grid;
  const gridSum = grid.reduce((s, w) => s + w, 0);
  const tblW = child(tblPr, 'tblW');
  const tableTwips = (attr(tblW, 'type') ?? 'dxa') === 'dxa' ? numAttr(tblW, 'w') ?? 0 : 0;
  let best: { widths: number[]; cells: number } | null = null;
  for (const tr of children(tbl, 'tr')) {
    const widths: number[] = new Array(grid.length).fill(0);
    let col = gridSkipOf(child(tr, 'trPr'), 'gridBefore');
    let ok = col === 0;
    let cells = 0;
    for (const tc of ok ? children(tr, 'tc') : []) {
      const tcPr = child(tc, 'tcPr');
      const span = gridSpanOf(tcPr);
      const tcW = child(tcPr, 'tcW');
      const type = attr(tcW, 'type') ?? 'dxa';
      let w = numAttr(tcW, 'w') ?? 0;
      // pct widths are fiftieths of a percent of the table width.
      if (type === 'pct') w = tableTwips ? (tableTwips * w) / 5000 : 0;
      else if (type !== 'dxa') w = 0;
      if (!(w > 0) || col + span > grid.length) {
        ok = false;
        break;
      }
      for (let k = 0; k < span; k++) widths[col + k] = w / span;
      col += span;
      cells++;
    }
    if (ok && col === grid.length && (!best || cells > best.cells)) best = { widths, cells };
  }
  // Only a clearly stale grid is replaced.
  if (best) {
    const sum = best.widths.reduce((s, w) => s + w, 0);
    return gridSum < sum * 0.6 ? best.widths.map((w) => Math.round(w)) : grid;
  }
  if (tableTwips && gridSum > 0 && gridSum < tableTwips * 0.6) return grid.map((w) => Math.round((w * tableTwips) / gridSum));
  return grid;
}

function pxWidths(grid: number[], from: number, n: number): number[] | null {
  const w = grid.slice(from, from + n).map((x) => Math.round(twipsToPx(x)));
  return w.length === n && w.every((x) => x > 0) ? w : null;
}

/** Join adjacent text nodes with equal marks (ProseMirror requires normalized text). */
export function mergeText(nodes: PMNode[]): PMNode[] {
  const out: PMNode[] = [];
  for (const n of nodes) {
    const prev = out[out.length - 1];
    if (prev && prev.isText && n.isText && prev.sameMarkup(n)) {
      out[out.length - 1] = schema.text(prev.text! + n.text!, prev.marks);
    } else out.push(n);
  }
  return out;
}

export { fieldKind };
