// Strict comparison of WordprocessingML parts.
//
// Two parts are "the same" when their element trees are identical after removing
// only differences Word itself doesn't care about:
//  - how text with identical formatting is split into runs,
//  - w:proofErr / w:lastRenderedPageBreak (regenerated by Word),
//  - namespace prefixes / declarations and xml:space on w:t.

import { NS } from '../../src/papyrus/docx/xml';

const DROP = new Set(['proofErr', 'lastRenderedPageBreak']);

interface Canon {
  name: string;
  attrs: string;
  text?: string;
  kids: Canon[];
}

function key(n: Element | Attr): string {
  return `${n.namespaceURI ?? ''}|${n.localName}`;
}

function attrsOf(el: Element): string {
  return Array.from(el.attributes)
    .filter((a) => a.prefix !== 'xmlns' && a.name !== 'xmlns' && !(a.localName === 'space' && a.namespaceURI === 'http://www.w3.org/XML/1998/namespace'))
    .map((a) => `${key(a)}=${a.value}`)
    .sort()
    .join(' ');
}

function canon(el: Element): Canon {
  const kids: Canon[] = [];
  for (const c of Array.from(el.children)) {
    if (c.namespaceURI === NS.w && DROP.has(c.localName)) continue;
    if (c.namespaceURI === NS.w && c.localName === 'r') kids.push(...explodeRun(c));
    else kids.push(canon(c));
  }
  const node: Canon = { name: key(el), attrs: attrsOf(el), kids: mergeRuns(kids) };
  if (!el.children.length && el.textContent) node.text = el.textContent;
  return node;
}

const RUN = `${NS.w}|r`;
const T = `${NS.w}|t`;

/** One run per content child, each carrying the run's attributes and rPr. */
function explodeRun(r: Element): Canon[] {
  const rPr = Array.from(r.children).find((c) => c.namespaceURI === NS.w && c.localName === 'rPr');
  const rPrCanon = rPr ? [canon(rPr)] : [];
  const out: Canon[] = [];
  for (const c of Array.from(r.children)) {
    if (c === rPr || (c.namespaceURI === NS.w && DROP.has(c.localName))) continue;
    if (c.namespaceURI === NS.w && c.localName === 't' && !c.textContent) continue; // empty text
    out.push({ name: RUN, attrs: attrsOf(r), kids: [...rPrCanon, canon(c)] });
  }
  return out;
}

/** Merge neighbouring text-only runs with identical formatting. */
function mergeRuns(kids: Canon[]): Canon[] {
  const out: Canon[] = [];
  for (const k of kids) {
    const prev = out[out.length - 1];
    const text = (c: Canon) => c.kids[c.kids.length - 1];
    if (
      prev && prev.name === RUN && k.name === RUN && prev.attrs === k.attrs &&
      text(prev)?.name === T && text(k)?.name === T &&
      JSON.stringify(prev.kids.slice(0, -1)) === JSON.stringify(k.kids.slice(0, -1))
    ) {
      const t = text(prev);
      out[out.length - 1] = { ...prev, kids: [...prev.kids.slice(0, -1), { ...t, text: (t.text ?? '') + (text(k).text ?? '') }] };
    } else out.push(k);
  }
  return out;
}

function short(c: Canon): string {
  const local = c.name.split('|')[1];
  return `<${local}${c.attrs ? ' ' + c.attrs.replace(/[^ ]*\|/g, '') : ''}>${c.text ? JSON.stringify(c.text.slice(0, 40)) : ''}`;
}

/** Differences between two elements, as readable paths (at most `limit`). */
export function compareElements(a: Element, b: Element, limit = 5): string[] {
  const out: string[] = [];
  const walk = (x: Canon, y: Canon, path: string) => {
    if (out.length >= limit) return;
    if (x.name !== y.name || x.attrs !== y.attrs || (x.text ?? '') !== (y.text ?? '')) {
      out.push(`${path}\n    original: ${short(x)}\n    saved:    ${short(y)}`);
      return;
    }
    const n = Math.max(x.kids.length, y.kids.length);
    for (let i = 0; i < n && out.length < limit; i++) {
      const p = `${path}/${(x.kids[i] ?? y.kids[i]).name.split('|')[1]}[${i}]`;
      if (!x.kids[i]) out.push(`${p}\n    original: (none)\n    saved:    ${short(y.kids[i])}`);
      else if (!y.kids[i]) out.push(`${p}\n    original: ${short(x.kids[i])}\n    saved:    (none)`);
      else walk(x.kids[i], y.kids[i], p);
    }
  };
  walk(canon(a), canon(b), a.localName);
  return out;
}
